info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bnanda/config-repo.git
#          uri: file:///Users/bnanda//Local-CF/config-repo
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/bnanda/config-repo
#              uri: file:///Users/bnanda//Local-CF/config-repo

server:
  port: 8888
management:
  context_path: /admin
